default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  prepared_statements: false

development:
  <<: *default
  database: csv_development

production:
  <<: *default
  host: <%= Rails.application.credentials.dig(:database_host) %>
  database: <%= Rails.application.credentials.dig(:database_database) %>
  username: <%= Rails.application.credentials.dig(:database_username) %>
  password: <%= Rails.application.credentials.dig(:database_password) %>
